import { PlatformAdapter, PlatformType, PublishContentInput, PublishResult, PublishStatus, PlatformHealthStatus, PlatformStats } from '../interfaces/platform-adapter.interface';
import type { PlatformConfig } from '../interfaces/platform-adapter.interface';
export declare class XHSAdapter implements PlatformAdapter {
    private readonly logger;
    private readonly http;
    private credentials;
    private config;
    private browserAgent;
    private isLoggedIn;
    constructor(config: PlatformConfig);
    getPlatformName(): string;
    getPlatformType(): PlatformType;
    initialize(): Promise<void>;
    healthCheck(): Promise<PlatformHealthStatus>;
    publishContent(content: PublishContentInput): Promise<PublishResult>;
    getPublishStatus(publishId: string): Promise<PublishStatus>;
    updateContent(publishId: string, content: Partial<PublishContentInput>): Promise<PublishResult>;
    deleteContent(publishId: string): Promise<void>;
    getPlatformStats(): Promise<PlatformStats>;
    cleanup(): Promise<void>;
    private initializeBrowserAgent;
    private loginWithSession;
    private loginWithCredentials;
    private publishWithBrowserAgent;
    private deleteNoteWithBrowserAgent;
    private formatXHSContent;
    private getNextMidnight;
    private delay;
    getUserProfile(): Promise<any>;
    getUserNotes(page?: number, pageSize?: number): Promise<any>;
}
