import { Repository } from 'typeorm';
import { CustomerProfile } from '../../../entities/customer-profile.entity';
import { CustomerSegment } from '../../../entities/customer-segment.entity';
import { DataImportJob } from '../../../entities/data-import-job.entity';
export declare class CustomerAnalyticsService {
    private customerProfileRepository;
    private customerSegmentRepository;
    private dataImportJobRepository;
    constructor(customerProfileRepository: Repository<CustomerProfile>, customerSegmentRepository: Repository<CustomerSegment>, dataImportJobRepository: Repository<DataImportJob>);
    generateCustomerProfileAnalysis(profileId: string): Promise<Record<string, any>>;
    private calculateDataFreshness;
    private calculateDataCompleteness;
    private generateDemographicAnalysis;
    private generateBehavioralAnalysis;
    private generateConsumptionAnalysis;
    private generateSegmentationAnalysis;
    private generateKeyInsights;
    private generateRecommendations;
    performCustomerSegmentation(profileId: string, segmentationRules?: Record<string, any>): Promise<CustomerSegment[]>;
    private getDefaultSegmentationRules;
    private generateSegmentationResults;
    getDashboardData(profileId: string): Promise<Record<string, any>>;
    getCustomerSegments(profileId: string): Promise<CustomerSegment[]>;
    getSegmentDetail(profileId: string, segmentId: string): Promise<CustomerSegment>;
    updateSegment(profileId: string, segmentId: string, updates: Partial<CustomerSegment>): Promise<CustomerSegment>;
    deleteSegment(profileId: string, segmentId: string): Promise<void>;
    getRadarChartData(profileId: string): Promise<Record<string, any>>;
    getScatterChartData(profileId: string): Promise<Record<string, any>>;
    getHeatmapChartData(profileId: string): Promise<Record<string, any>>;
    getFunnelChartData(profileId: string): Promise<Record<string, any>>;
    getSankeyChartData(profileId: string): Promise<Record<string, any>>;
    getAllChartData(profileId: string): Promise<Record<string, any>>;
    private calculateYoungCustomerRatio;
    private calculateFemaleCustomerRatio;
    private calculateLocalCustomerRatio;
    private calculateSpendingLevel;
    private calculateActivityLevel;
    private calculateLoyaltyLevel;
    private getIndustryBenchmark;
    private assignCustomerSegment;
    private calculateCorrelation;
    private identifyPeakPeriods;
    private identifyFunnelBottlenecks;
    private calculateNetGrowth;
}
