import { GeminiService } from './gemini.service';
import { ContentGenerationOptions, MarketingContentOptions, GeneratedContent, ContentGenerationResult, ContentTemplate, ContentQualityAssessment } from '../interfaces/content-generation.interface';
import { Platform } from '../../../shared/enums/platform.enum';
export declare class ContentGenerationService {
    private readonly geminiService;
    private readonly logger;
    private contentTemplates;
    constructor(geminiService: GeminiService);
    generateContent(options: ContentGenerationOptions): Promise<ContentGenerationResult>;
    generateMarketingContent(options: MarketingContentOptions): Promise<ContentGenerationResult>;
    generateContentWithTemplate(templateId: string, templateVariables: Record<string, string>, customOptions?: Partial<ContentGenerationOptions>): Promise<ContentGenerationResult>;
    batchGenerateContent(optionsList: ContentGenerationOptions[]): Promise<ContentGenerationResult[]>;
    assessContentQuality(content: GeneratedContent, platform: Platform): Promise<ContentQualityAssessment>;
    getAllTemplates(): ContentTemplate[];
    getTemplatesByPlatform(platform: Platform): ContentTemplate[];
    getTemplatesByType(templateType: string): ContentTemplate[];
    addTemplate(template: Omit<ContentTemplate, 'id' | 'createdAt' | 'updatedAt'>): ContentTemplate;
    updateTemplate(templateId: string, updates: Partial<Omit<ContentTemplate, 'id' | 'createdAt'>>): ContentTemplate | null;
    deleteTemplate(templateId: string): boolean;
    private enhanceQualityAssessment;
    private performBaseQualityAssessment;
    private evaluatePlatformFit;
    private evaluatePlatformSpecificQuality;
    private evaluateCrossPlatformConsistency;
    private optimizePostingSchedule;
    private evaluateEngagementPotential;
    private evaluateConversionPotential;
    private generateDetailedFeedback;
    private generateEnhancedFeedback;
    private generateBasicImprovementSuggestions;
    private generateDetailedImprovementSuggestions;
    private increaseFrequency;
    private decreaseFrequency;
    private countInteractiveElements;
    private checkTrendingKeywords;
    private evaluateContentDepth;
    private countProfessionalTerms;
    private evaluateContentValue;
    private extractMainTheme;
    private calculateThemeSimilarity;
    private countEmotionalWords;
    private countPurchaseWords;
    private countSeedingWords;
}
