import { OnModuleInit } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { GeminiStrategyResponse, GeminiError, GeminiGenerateOptions } from '../interfaces/gemini.interface';
import { ContentGenerationOptions, MarketingContentOptions, ContentGenerationResult } from '../interfaces/content-generation.interface';
export declare class GeminiService implements OnModuleInit {
    private configService;
    private readonly logger;
    private config;
    private isAvailable;
    private apiKeys;
    private currentKeyIndex;
    private keyFailures;
    private maxFailuresPerKey;
    private keyRotationMode;
    constructor(configService: ConfigService);
    onModuleInit(): Promise<void>;
    private parseApiKeys;
    private getNextApiKey;
    private recordKeyFailure;
    private resetKeyFailure;
    private rotateToNextKey;
    private initializeWithCurrentKey;
    private initialize;
    isGeminiAvailable(): boolean;
    checkGeminiHealth(retryCount?: number): Promise<{
        available: boolean;
        error?: string;
        details?: any;
        apiKeys?: {
            total: number;
            available: number;
            currentIndex: number;
            failures: Record<string, number>;
        };
    }>;
    generateMarketingStrategy(options: GeminiGenerateOptions): Promise<{
        success: boolean;
        data?: GeminiStrategyResponse;
        error?: GeminiError;
        fallbackUsed?: boolean;
        isTruncated?: boolean;
    }>;
    private buildStrategyPrompt;
    private cleanJsonResponse;
    private repairTruncatedJson;
    private parseGeminiResponse;
    private tryRepairJson;
    private ensureJsonClosed;
    private repairJsonString;
    private emergencyJsonRepair;
    private generateFallbackStrategy;
    generateContent(options: ContentGenerationOptions): Promise<ContentGenerationResult>;
    generateMarketingContent(options: MarketingContentOptions): Promise<ContentGenerationResult>;
    private buildContentPrompt;
    private buildMarketingContentPrompt;
    private parseContentResponse;
    private assessContentQuality;
    private getPlatformFitScore;
    private generateQualityFeedback;
    private generateImprovementSuggestions;
    private getPlatformInstructions;
    private getToneInstructions;
    private getBestPostingTimes;
    private getRecommendedFrequency;
    private calculateConsistencyScore;
    private calculateStringSimilarity;
    private generateContentStrategySummary;
    private generateContentViaRest;
    private generateFallbackContent;
    private generateFallbackMarketingContent;
}
