import { ConfigService } from '@nestjs/config';
import { EnterpriseProfile } from '../../../entities/enterprise-profile.entity';
import { EnterpriseProfileRepository } from '../../../shared/repositories/enterprise-profile.repository';
import { CustomerProfileRepository } from '../../../shared/repositories/customer-profile.repository';
import { KnowledgeRetrievalService } from '../../ai-engine/agents/analysis/services/knowledge-retrieval.service';
import { VectorSearchService } from '../../../shared/vector/services/vector-search.service';
export declare class EnterpriseProfileAnalysisService {
    private enterpriseProfileRepository;
    private customerProfileRepository;
    private knowledgeRetrievalService;
    private vectorSearchService;
    private configService;
    private readonly logger;
    private aiService;
    constructor(enterpriseProfileRepository: EnterpriseProfileRepository, customerProfileRepository: CustomerProfileRepository, knowledgeRetrievalService: KnowledgeRetrievalService, vectorSearchService: VectorSearchService, configService: ConfigService);
    private initializeAIService;
    createAnalysisTask(customerProfileId: string): Promise<EnterpriseProfile>;
    private startAnalysisTask;
    private collectKnowledgeData;
    private extractEnterpriseFeatures;
    private generateProfileData;
    private calculateFeatureVector;
    private completeAnalysis;
    getProfile(profileId: string): Promise<EnterpriseProfile>;
    getProfilesByCustomer(customerProfileId: string): Promise<EnterpriseProfile[]>;
    getCurrentProfile(customerProfileId: string): Promise<EnterpriseProfile | null>;
    reanalyzeProfile(profileId: string): Promise<EnterpriseProfile>;
    getAnalysisStatus(profileId: string): Promise<{
        status: string;
        progress: number;
        estimatedTime?: number;
        errorMessage?: string;
    }>;
    batchAnalyzeProfiles(customerProfileIds: string[]): Promise<EnterpriseProfile[]>;
    private extractIndustryCharacteristics;
    private analyzeCompetitivePosition;
    private identifyContentStrategyPatterns;
    private generateFeatureVectorFromProfile;
    private hashString;
    private createEmptyProfileData;
}
