export declare enum CustomerType {
    ENTERPRISE = "ENTERPRISE",
    SME = "SME",
    INDIVIDUAL_BUSINESS = "INDIVIDUAL_BUSINESS",
    INDIVIDUAL = "INDIVIDUAL",
    GOVERNMENT = "GOVERNMENT",
    NON_PROFIT = "NON_PROFIT"
}
