export declare enum UserRole {
    SUPER_ADMIN = "SUPER_ADMIN",
    ADMIN = "ADMIN",
    CONTENT_MANAGER = "CONTENT_MANAGER",
    CONTENT_EDITOR = "CONTENT_EDITOR",
    MARKETING_MANAGER = "MARKETING_MANAGER",
    LEGAL_REVIEWER = "LEGAL_REVIEWER",
    VIEWER = "VIEWER",
    GUEST = "GUEST"
}
