export declare enum UserBehaviorEvent {
    PAGE_VIEW = "PAGE_VIEW",
    CONTENT_CREATE = "CONTENT_CREATE",
    PUBLISH_TASK = "PUBLISH_TASK",
    LOGIN = "LOGIN",
    LOGOUT = "LOGOUT",
    CAMPAIGN_CREATE = "CAMPAIGN_CREATE",
    STRATEGY_GENERATE = "STRATEGY_GENERATE",
    REPORT_VIEW = "REPORT_VIEW"
}
