export declare enum WorkflowStatus {
    DRAFT = "DRAFT",
    EDITOR_REVIEW = "EDITOR_REVIEW",
    AI_CHECK = "AI_CHECK",
    MANAGER_REVIEW = "MANAGER_REVIEW",
    LEGAL_REVIEW = "LEGAL_REVIEW",
    APPROVED = "APPROVED",
    PUBLISHED = "PUBLISHED",
    COMPLETED = "COMPLETED",
    REJECTED = "REJECTED",
    NEEDS_REVISION = "NEEDS_REVISION",
    WITHDRAWN = "WITHDRAWN",
    CANCELLED = "CANCELLED"
}
export declare enum ApprovalNodeType {
    EDITOR = "EDITOR",
    AI = "AI",
    MANAGER = "MANAGER",
    LEGAL = "LEGAL",
    PARALLEL = "PARALLEL",
    SEQUENTIAL = "SEQUENTIAL"
}
export declare enum ApprovalAction {
    APPROVE = "APPROVE",
    REJECT = "REJECT",
    RETURN_FOR_REVISION = "RETURN_FOR_REVISION",
    TRANSFER = "TRANSFER",
    EXPEDITE = "EXPEDITE"
}
export declare enum NotificationType {
    TASK_ASSIGNED = "TASK_ASSIGNED",
    PENDING_APPROVAL = "PENDING_APPROVAL",
    APPROVAL_COMPLETED = "APPROVAL_COMPLETED",
    APPROVAL_TIMEOUT = "APPROVAL_TIMEOUT",
    WORKFLOW_STATUS_CHANGED = "WORKFLOW_STATUS_CHANGED",
    URGENT_APPROVAL = "URGENT_APPROVAL"
}
