import { Workflow } from './workflow.entity';
import { WorkflowNode } from './workflow-node.entity';
import { User } from '../../../entities/user.entity';
import { NotificationType } from '../../../shared/enums/workflow-status.enum';
export declare class Notification {
    id: string;
    tenantId: string;
    type: NotificationType;
    recipientId: string;
    recipient: User;
    workflowId: string;
    workflow: Workflow;
    nodeId: string;
    node: WorkflowNode;
    title: string;
    content: string;
    status: string;
    channels: string[];
    sentAt: Date;
    readAt: Date;
    actionedAt: Date;
    priority: number;
    isSilent: boolean;
    isRecurring: boolean;
    recurrenceInterval: number;
    nextSendAt: Date;
    retryCount: number;
    maxRetries: number;
    failureReason: string;
    metadata: {
        actionUrl?: string;
        deepLink?: string;
        templateId?: string;
        variables?: Record<string, any>;
        category?: string;
        tags?: string[];
    };
    createdAt: Date;
    updatedAt: Date;
}
