import { Repository } from 'typeorm';
import { GeoRegion } from '../entities/geo-region.entity';
import { GeoAnalysisResult } from '../entities/geo-analysis-result.entity';
import { SeoSuggestion } from '../entities/seo-suggestion.entity';
import { RegionAnalysisService } from './region-analysis.service';
import { CompetitiveAnalysisService } from './competitive-analysis.service';
import { SeoSuggestionService } from './seo-suggestion.service';
import { GeoAnalysisResponse } from '../interfaces/geo-analysis.interface';
import { GeoAnalysisRequestDto } from '../dto/geo-analysis-request.dto';
export declare class GeoAnalysisService {
    private readonly geoRegionRepository;
    private readonly geoAnalysisResultRepository;
    private readonly seoSuggestionRepository;
    private readonly regionAnalysisService;
    private readonly competitiveAnalysisService;
    private readonly seoSuggestionService;
    private readonly logger;
    constructor(geoRegionRepository: Repository<GeoRegion>, geoAnalysisResultRepository: Repository<GeoAnalysisResult>, seoSuggestionRepository: Repository<SeoSuggestion>, regionAnalysisService: RegionAnalysisService, competitiveAnalysisService: CompetitiveAnalysisService, seoSuggestionService: SeoSuggestionService);
    analyze(request: GeoAnalysisRequestDto): Promise<GeoAnalysisResponse>;
    private executeAnalysis;
    private getTargetRegions;
    private identifyOpportunities;
    private analyzeTrends;
    private calculateOverallScore;
    private extractKeyFindings;
    private generateVisualizations;
    private generateRecommendations;
    private calculateMarketCoverage;
    private assessEntryDifficulty;
    private generateMarketEntryStrategy;
    private identifyProductGaps;
    private identifyPartnershipOpportunities;
    private identifyInnovationAreas;
    private generateHistoricalData;
    private generateForecastData;
    getAnalysisResult(analysisId: string): Promise<GeoAnalysisResult>;
    getRegions(tenantId: string, filters?: any): Promise<GeoRegion[]>;
    getSeoSuggestions(tenantId: string, filters?: any): Promise<SeoSuggestion[]>;
}
