import { GeoRegion } from '../entities/geo-region.entity';
import { GeoAnalysisRequestDto } from '../dto/geo-analysis-request.dto';
export declare class RegionAnalysisService {
    private readonly logger;
    analyzeRegions(regions: GeoRegion[], request: GeoAnalysisRequestDto): Promise<any>;
    private analyzeDemographics;
    private analyzeEconomy;
    private analyzeCulture;
    private analyzeDigital;
    private identifyStrengths;
    private identifyWeaknesses;
    private calculateDemographicScore;
    private assessDemographicGrowthPotential;
    private calculateConsumptionIndex;
    private calculateInvestmentIndex;
    private assessEconomicStability;
    private determineDevelopmentStage;
    private parseLanguageData;
    private parseReligionData;
    private inferCulturalValues;
    private estimateMediaConsumption;
    private estimateEntertainmentPreferences;
    private assessCulturalOpenness;
    private assessTraditionModernityBalance;
    private estimateDigitalPaymentUsage;
    private estimateOnlineTime;
    private estimatePreferredDevices;
    private assessDigitalLiteracy;
    private assessInnovationAdoption;
    private getYoungPopulationRatio;
    private getAgingPopulationRatio;
    private generateDemographicSummary;
    private getYoungPopulationRatioFromData;
    private extractDemographicInsights;
    private generateEconomicSummary;
    private extractEconomicInsights;
    private generateCulturalSummary;
    private extractCulturalInsights;
    private generateDigitalSummary;
    private extractDigitalInsights;
    private selectComparisonMetrics;
    private rankRegions;
    private calculateRegionScores;
    private calculateEconomicScore;
    private calculateCulturalScore;
    private calculateDigitalScore;
    private calculateCompetitiveScore;
}
