import { ConfigService } from '@nestjs/config';
import { GovernmentContent, GovernmentContentRequest, GovernmentContentResponse, ComplianceCheckResult, GovernmentContentTemplate, GovernmentScenarioScript, GovernmentContentStats } from '../interfaces/government-content.interface';
export declare class GovernmentContentService {
    private readonly configService;
    private readonly logger;
    private readonly templates;
    private readonly scripts;
    private readonly stats;
    constructor(configService: ConfigService);
    generateContent(request: GovernmentContentRequest): Promise<GovernmentContentResponse>;
    private generateOfficialDocument;
    private generateAntiFraudContent;
    private generatePolicyInterpretationContent;
    private generateGovernmentServiceContent;
    private generatePublicAnnouncementContent;
    private generateEmergencyResponseContent;
    checkCompliance(content: GovernmentContent): Promise<ComplianceCheckResult>;
    private containsSensitiveWords;
    private checkFormat;
    private checkRequiredElements;
    private checkOfficialDocumentCompliance;
    private checkAntiFraudCompliance;
    private checkPolicyInterpretationCompliance;
    private getSuggestedPlatforms;
    private generateContentSummary;
    getTemplates(): GovernmentContentTemplate[];
    getScripts(): GovernmentScenarioScript[];
    getStats(): GovernmentContentStats;
    private initializeTemplates;
    private initializeScripts;
}
