import { ConfigService } from '@nestjs/config';
import { MetricsCollectorService } from '../metrics/collectors/metrics-collector.service';
import { AlertRuleService } from '../alerts/rules/alert-rule.service';
import { ReportDefinition, ReportInstance, ReportFormat } from '../interfaces/reports.interface';
export declare class PerformanceReportService {
    private configService;
    private metricsCollector;
    private alertRuleService;
    private readonly logger;
    private reportDefinitions;
    private reportInstances;
    private readonly maxReportInstances;
    constructor(configService: ConfigService, metricsCollector: MetricsCollectorService, alertRuleService: AlertRuleService);
    private initializeReportDefinitions;
    generateDailyPerformanceReport(): Promise<void>;
    generateWeeklyBusinessReport(): Promise<void>;
    generateMonthlySummaryReport(): Promise<void>;
    generatePerformanceHealthReport(): Promise<void>;
    generateReport(definitionId: string, format: ReportFormat): Promise<ReportInstance | null>;
    private generateReportContent;
    private collectPerformanceMetrics;
    private collectBusinessMetrics;
    private collectAlertStatistics;
    private identifyIssues;
    private analyzeTrends;
    private generateRecommendations;
    private generateSummary;
    private generateReportFile;
    private estimateFileSize;
    private deliverReport;
    private cleanupOldReports;
    private calculatePercentile;
    private calculateThroughput;
    private estimateConcurrentUsers;
    private estimateCpuUsage;
    private estimateMemoryUsage;
    private estimateNewUsers;
    private estimateDatabaseQueries;
    private estimatePublishSuccessRate;
    private estimateUserSatisfaction;
    getReportDefinitions(): ReportDefinition[];
    getReportInstances(limit?: number): ReportInstance[];
    triggerReportGeneration(definitionId: string, format?: ReportFormat): Promise<ReportInstance | null>;
}
