import { MarketingCampaign } from './marketing-campaign.entity';
import { CustomerProfile } from '../../../entities/customer-profile.entity';
import { StrategyType } from '../../../shared/enums/strategy-type.enum';
import { GenerationMethod } from '../../../shared/enums/generation-method.enum';
import { Platform } from '../../../shared/enums/platform.enum';
import { AIEngine } from '../interfaces/gemini.interface';
import { TenantEntity } from '../../../shared/interfaces/tenant-entity.interface';
export declare class MarketingStrategy implements TenantEntity {
    id: string;
    tenantId: string;
    campaignId: string;
    campaign: MarketingCampaign;
    customerProfileId: string;
    customerProfile: CustomerProfile;
    strategyType: StrategyType;
    description: string;
    implementationPlan: Record<string, any>;
    expectedROI: string;
    confidenceScore: string;
    generatedBy: GenerationMethod;
    createdAt: Date;
    campaignName: string;
    targetAudienceAnalysis: Record<string, any>;
    coreIdea: string;
    xhsContent: string;
    wechatFullPlan: Record<string, any>;
    recommendedExecutionTime: Record<string, any>;
    expectedPerformanceMetrics: Record<string, any>;
    executionSteps: Record<string, any>;
    riskAssessment: Record<string, any>;
    budgetAllocation: Record<string, any>;
    aiResponseRaw: string;
    aiEngine: AIEngine;
    generatedContentIds: string[];
    contentPlatforms: Platform[];
}
