import { OnModuleInit } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { MetricsCollectorService } from '../../metrics/collectors/metrics-collector.service';
import { AlertRule, AlertInstance } from '../../interfaces/alerts.interface';
export declare class AlertRuleService implements OnModuleInit {
    private configService;
    private metricsCollector;
    private readonly logger;
    private rules;
    private alerts;
    private channels;
    private readonly alertHistorySize;
    constructor(configService: ConfigService, metricsCollector: MetricsCollectorService);
    onModuleInit(): Promise<void>;
    private initializeRules;
    private initializeChannels;
    checkAllRules(): Promise<void>;
    private evaluateRule;
    private evaluateCondition;
    private aggregateMetrics;
    private calculatePercentile;
    private applyOperator;
    private triggerAlert;
    private sendAlertNotifications;
    private sendNotification;
    getRules(): AlertRule[];
    getActiveAlerts(): AlertInstance[];
    getAlertHistory(limit?: number): AlertInstance[];
    markAlertAsRecovered(alertId: string): void;
    upsertRule(rule: AlertRule): void;
    deleteRule(ruleId: string): boolean;
    checkRule(ruleId: string): Promise<boolean>;
}
